sudo: required
services:
  - docker

before_install:
  - docker build -t nathandanielpeterson/fib-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nathandanielpeterson/fib-docker-test npm test -- --coverage

after_success:
  - docker build -t fib-client ./client
  - docker build -t fib-server ./server
  - docker build -t fib-nginx ./nginx
  - docker build -t fib-worker ./worker
  # Log into dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push fib-client
  - docker push fib-server
  - docker push fib-worker
  - docker push fib-nginx
  