sudo: required
services:
  - docker

before_install:
  - docker build -t nathandanielpeterson/fib-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nathandanielpeterson/fib-docker-test npm test -- --coverage

after_success:
  - docker build -t nathandanielpeterson/fib-client ./client
  - docker build -t nathandanielpeterson/fib-server ./server
  - docker build -t nathandanielpeterson/fib-nginx ./nginx
  - docker build -t nathandanielpeterson/fib-worker ./worker
  # Log into dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push nathandanielpeterson/fib-client
  - docker push nathandanielpeterson/fib-server
  - docker push nathandanielpeterson/fib-worker
  - docker push nathandanielpeterson/fib-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: fib-docker
  env: FibDocker-env
  bucket_name: elasticbeanstalk-us-east-2-765940356773
  bucket_path: fib-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY